# Generated by Django 3.0.2 on 2020-02-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(max_length=3000)),
                ('postimage', models.FileField(blank=True, null=True, upload_to='')),
                ('postdate', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=80)),
                ('detail_link', models.CharField(max_length=200)),
            ],
        ),
    ]
